drop table if exists member casecade;
drop table if exists article casecade;
drop table if exists comment casecade;

create table member
    {
        id bigint generated by default as identity,
        email varchar(255),
        password varchar(255),
    }

create table article
    {
        id bigint generated by default as identity,
        member_id bigint,
        title varchar(255),
        content varchar(255),
        foreign key member_id
        references member(id)
    }
create table comment
    {
        id bigint generated by default as identity,
        article_id bigint,
        nickname varchar(255),
        body varchar(255),
        foreign key article_id
        references article(id)
    }